// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uzxklikcclhhgxgzatyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6eGtsaWtjY2xoaGd4Z3phdHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MjQ3MTIsImV4cCI6MjA4OTUwMDcxMn0.sCZJohoNa4DcsRBxTvRN-OHqOadlT1g1lfwkIloY5xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
